version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - checkout 
      - run:
          name: The First Step
          command: |
            echo 'test'
      - run: 
          name: List files
          commandL: |
             ls -al
          
