version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: The First Step
          command: |
            echo 'test'
      - run: 
          name: List files
          commandL: |
             ls -al
          
